services: 
  mongo:
    container_name: mongo
    image: mongo
    ports:    
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongosrv
    volumes:
      - /mnt/docker-pratica/volumes/MongoDB:/data/db
    networks:
      - minhafrontend

networks:
  minhafrontend:
    driver: bridge